AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Project:
    Type: String
  Environment:
    Type: String

Resources: 

  # InitStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: ./init.yml
  #     Parameters:
  #       Project: !Ref Project
  #       Environment: !Ref Environment
  #       EcsTaskExecutionRole: !ImportValue account-commons-EcsTaskExecutionRole

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./network.yml
      Parameters:
        Project: !Ref Project
        Environment: !Ref Environment

  ServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./service.yml
      Parameters:
        Project: !Ref Project
        Environment: !Ref Environment

